### ISSUE TITLE
Bottom overflowed by 10 pixels

### ISSUE THREAD

**Issue by uditparmar** [abuanwar072/E-commerce-Complete-Flutter-UI#15]
Hello, I am new to flutter technology and just started to learn. I was trying to find some flutter template app to get started and I found your e-commerce UI app. This is really great and very useful for me. I just pulled latest changes, and I got this error in ui: Bottom overflowed by 10 pixels. I am using oneplus 8 for debugging and I think I got this error because of large screen. Can you please check it out and give me your suggestion. I have also attached error screen shot here. Error is shown at the bottom of page with yellow and black lines
![Screenshot_20200928-144836](https://user-images.githubusercontent.com/43785560/94416046-f52f2b80-019b-11eb-822b-cfc29bb818ad.jpg)

**Comment by Bavon101** [comment]
use a listview as the parent widget or a put them in a scrollview
