### ISSUE TITLE
Responsivity problem

### ISSUE THREAD

**Issue by brakenseddik** [abuanwar072/E-commerce-Complete-Flutter-UI#18]
I have a problem with responsivity my device is 5.2" but there are problems in displaying elements related to padding and margin !!

**Comment by acarolsf** [comment]
![](https://user-images.githubusercontent.com/22717833/105533520-02cc6c00-5ccb-11eb-8a0a-74dc42dc9574.png)

**Comment by SatYu26** [comment]
@brakenseddik  where are you facing this issue.
you can try doing `mediaquery.of(context).size.width`
