### ISSUE TITLE
LinearGradient throws an error

### ISSUE THREAD

**Issue by LebToki** [abuanwar072/E-commerce-Complete-Flutter-UI#25]
const kPrimaryGradientColor = LinearGradient(
  begin: Alignment.topLeft,
  end: Alignment.bottomRight,
  colors: [Color(0xFFFFA53E), Color(0xFFFF7643)],
);

it should be wrapped in a gradient() 
how to fix this ?

**Comment by SatYu26** [comment]
@LebToki can u please elaborate where you have got this issue?  and how u got it?

**Comment by LebToki** [comment]
Hi
Will try to reproduce it and get back to you
