### ISSUE TITLE
CustomAppBar issues

### ISSUE THREAD

**Issue by osama3101995** [abuanwar072/E-commerce-Complete-Flutter-UI#42]
I have been able to fix almost all of the 2.2.0 flutter migration issues. However, I cannot for the life of mine, fix this. Is anyone else recieving the issue on PreferredSize?

Error: The superclass 'PreferredSize' doesn't have a zero argument constructor.

Not sure what I should do to fix it?

**Comment by 69-69** [comment]
>  Remove the @ from the required `CustomAppBar({@required this.rating});`
> Implement `class CustomAppBar extends StatelessWidget implements PreferredSizeWidget {
` instead this `class CustomAppBar extends PreferredSize {`

And it done

**Comment by abuanwar072** [comment]
Recent commit fixed it!
